import "./globals.scss";

import { Lato, Roboto } from "next/font/google";

import Footer from "@/app/Components/Footer";
// import Header from "@/app/Components/Header";
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import background1 from "@/assets/background.svg";
import logo from "@/assets/logo.svg";

const robotoSans = Roboto({
  weight: ["300", "400", "500"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const latoSans = Lato({
  weight: ["300", "400", "700"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable}  ${latoSans.variable} antialiased`}>
        <div className="md:shadow-slate-200/50 md:shadow-xl bg-white">
          <main className="mb-20">
            {/* i originally had Header as its own component, sister to main el, but due to the pos abs of the background blob, moved it here */}
            <div className="header z-10 relative">
              <nav>
                <Link href={"/"} className="z-10 absolute">
                  <Image src={logo} alt="Agency Analytics logo" />
                </Link>
                <div className="absolute background">
                  <Image src={background1} alt="" />
                </div>
              </nav>
            </div>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
