import "./globals.css";

import { Lato, Roboto } from "next/font/google";

import type { Metadata } from "next";

const robotoSans = Roboto({
  weight: ["300", "400", "500"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const latoSans = Lato({
  weight: ["300", "400"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable}  ${latoSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
